using Microsoft.ML.Data;

namespace CustomerBehaviour.Definitions
{
    public class Customer
    {
        public float target { get; set; }
        public float Field1 { get; set; }
        public float Field2 { get; set; }
        public float Field3 { get; set; }
        public float Field4 { get; set; }
        public float Field5 { get; set; }
        public float Field6 { get; set; }
        public float Field7 { get; set; }
        public float Field8 { get; set; }
        public float Field9 { get; set; }
        public float Field10 { get; set; }
        public float Field11 { get; set; }
        public float Field12 { get; set; }
        public float Field13 { get; set; }
        public float Field14 { get; set; }
        public float Field15 { get; set; }
        public float Field16 { get; set; }
        public float Field17 { get; set; }
        public float Field18 { get; set; }
        public float Field19 { get; set; }
        public float Field20 { get; set; }
        public float Field21 { get; set; }
        public float Field22 { get; set; }
        public float Field23 { get; set; }
        public float Field24 { get; set; }
        public float Field25 { get; set; }
        public float Field26 { get; set; }
        public float Field27 { get; set; }
        public float Field28 { get; set; }
        public float Field29 { get; set; }
        public float Field30 { get; set; }
        public float Field31 { get; set; }
        public float Field32 { get; set; }
        public float Field33 { get; set; }
        public float Field34 { get; set; }
        public float Field35 { get; set; }
        public float Field36 { get; set; }
        public float Field37 { get; set; }
        public float Field38 { get; set; }
        public float Field39 { get; set; }
        public float Field40 { get; set; }
        public float Field41 { get; set; }
        public float Field42 { get; set; }
        public float Field43 { get; set; }
        public float Field44 { get; set; }
        public float Field45 { get; set; }
        public float Field46 { get; set; }
        public float Field47 { get; set; }
        public float Field48 { get; set; }
        public float Field49 { get; set; }
        public float Field50 { get; set; }
        public float Field51 { get; set; }
        public float Field52 { get; set; }
        public float Field53 { get; set; }
        public float Field54 { get; set; }
        public float Field55 { get; set; }
        public float Field56 { get; set; }
        public float Field57 { get; set; }
        public float Field58 { get; set; }
        public float Field59 { get; set; }
        public float Field60 { get; set; }
        public float Field61 { get; set; }
        public float Field62 { get; set; }
        public float Field63 { get; set; }
        public float Field64 { get; set; }
        public float Field65 { get; set; }
        public float Field66 { get; set; }
        public float Field67 { get; set; }
        public float Field68 { get; set; }
        public float Field69 { get; set; }
        public float Field70 { get; set; }
        public float Field71 { get; set; }
        public float Field72 { get; set; }
        public float Field73 { get; set; }
        public float Field74 { get; set; }
        public float Field75 { get; set; }
        public float Field76 { get; set; }
        public float Field77 { get; set; }
        public float Field78 { get; set; }
        public float Field79 { get; set; }
        public float Field80 { get; set; }
        public float Field81 { get; set; }
        public float Field82 { get; set; }
        public float Field83 { get; set; }
        public float Field84 { get; set; }
        public float Field85 { get; set; }
        public float Field86 { get; set; }
        public float Field87 { get; set; }
        public float Field88 { get; set; }
        public float Field89 { get; set; }
        public float Field90 { get; set; }
        public float Field91 { get; set; }
        public float Field92 { get; set; }
        public float Field93 { get; set; }
        public float Field94 { get; set; }
        public float Field95 { get; set; }
        public float Field96 { get; set; }
        public float Field97 { get; set; }
        public float Field98 { get; set; }
        public float Field99 { get; set; }
        public float Field100 { get; set; }
        public float Field101 { get; set; }
        public float Field102 { get; set; }
        public float Field103 { get; set; }
        public float Field104 { get; set; }
        public float Field105 { get; set; }
        public float Field106 { get; set; }
        public float Field107 { get; set; }
        public float Field108 { get; set; }
        public float Field109 { get; set; }
        public float Field110 { get; set; }
        public float Field111 { get; set; }
        public float Field112 { get; set; }
        public float Field113 { get; set; }
        public float Field114 { get; set; }
        public float Field115 { get; set; }
        public float Field116 { get; set; }
        public float Field117 { get; set; }
        public float Field118 { get; set; }
        public float Field119 { get; set; }
        public float Field120 { get; set; }
        public float Field121 { get; set; }
        public float Field122 { get; set; }
        public float Field123 { get; set; }
        public float Field124 { get; set; }
        public float Field125 { get; set; }
        public float Field126 { get; set; }
        public float Field127 { get; set; }
        public float Field128 { get; set; }
        public float Field129 { get; set; }
        public float Field130 { get; set; }
        public float Field131 { get; set; }

    }
}